repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.30.0
    hooks:
      - id: eslint
        name: eslint
        entry: eslint --config .eslintrc.json --max-warnings=0
        files: \.(js|jsx|ts|tsx)$
        types: [file]
